### ISSUE TITLE
TypeError: Cannot read property 'position' of undefined (Bi-directional loop)

### ISSUE THREAD

**Issue by baktash93** [Ideolys/carbone#45]
Greetings. 
I am trying to use the _bi-directional_ loop with an `.odt` file but can't seem to get it working as I've started with the provided examples in the [docs](https://carbone.io/designer-documentation.html#bi-directionnal-loop) but it doesn't work as expected and produces the following error:

    TypeError: Cannot read property 'position' of undefined
    at Object.splitMarkers (<project>/node_modules/carbone/lib/extracter.js:228:41)
    at <project>/node_modules/carbone/lib/builder.js:41:50
    at Object.preprocessMarkers (<project>/node_modules/carbone/lib/parser.js:286:5)
    at <project>/node_modules/carbone/lib/builder.js:38:18
    at <project>/node_modules/carbone/lib/parser.js:39:7
    at process._tickCallback (internal/process/next_tick.js:61:11)

Your quick response and help is very much appreciated.

**Comment by Dobby85** [comment]
Hi, can you give your template and your sample JSON so we can try to reproduce it ?

**Comment by baktash93** [comment]
Yeah sure, the `.odt` is the same as the one from the online example:

    

     {d[i].models[i].brand} | {d[i+1].models[i].brand}
     {d[i].models[i].name} | {d[i+1].models[i].name}
     {d[i].models[i+1].name } | {d[i+1].models[i+1].name }



And the data supplied to the `.odt` is as follows:

    [
      {
        "brand" : "Toyota",
        "models": [ 
          {"name" : "Prius 2" }, 
          {"name" : "Prius 3" }
        ]
      },
      {
        "brand" : "Tesla",
        "models" : [ 
          {"name" : "S" }, 
          {"name" : "X" }
        ]
      },
      {
        "brand" : "Lumeneo",
        "models" : [ 
          {"name" : "Smera" }, 
          {"name" : "Néoma" }
        ]
      }
    ]

**Comment by Dobby85** [comment]
It looks like there is a bug with that... We already know bi-directional loop does not work in .ods file but looping on a simple array does not work too. We will try to find a solution as soon as possible!

**Comment by baktash93** [comment]
OK looking forward to it.

**Comment by steevepay** [comment]
Hi @baktash93 

Just to give you some updates, we will fix this issue maybe on the next release.
If you can't wait the fix, feel free to fork the project and contribute :)

**Comment by JosselinTD** [comment]
I had it working with this :

{d.title[i].text} | {d.title[i+1].text}
-- | --
{d.content[i].content[i].text} | {d.content[i].content[i+1].text}
{d.content[i+1].content[i].text} | {d.content[i+1].content[i+1].text}

```
{
  title: [{text: 'Salutation'}, {text: 'lang'}],
  content: [
    {content: [{text: 'Hello'}, {text: 'en'}]},
    {content: [{text: 'Bonjour'}, {text: 'fr'}]}
  ]
}
```
I never use a direct value from an array. `Array` contains `Object` which contains the value to use.

For the doc example, try by using something like that :
```
{
  myArray : [{"brand": etc...}, {"brand": etc...]
}
```
and changing the template with `d.myArray[i]`

**Comment by waltermaldonado** [comment]
> content: [
>     {content: [{text: 'Hello'}, {text: 'en'}]},
>     {content: [{text: 'Bonjour'}, {text: 'fr'}]}
>   ]

I managed to make it work like the example, but if you add another column to the data it does not get redered...

**Comment by tomspeed22** [comment]
Hello, 
Is there a workaround to accomodate unlimited amount of Rows and Column. When applying the fix on 3 Columns it does not render. Here is the example.
Thanks
======================
======================

{d.cars[i].brand} | {d.cars[i+1].brand}
{d.models[i].models[i].name} | {d.models[i].models[i+1].name}
{d.models[i+1].models[i].name} | {d.models[i+1].models[i+1].name}

======================
======================

{
	"cars": [
		{
			"brand": "Toyota"
		},
		{
			"brand": "Testla"
		},
		{
			"brand": "Permeo"
		}
	],
	"models": [
		{
			"models": [
				{
					"name": "Prius 2"
				},
				{
					"name": "Prius 3"
				}
			]
		},
		{
			"models": [
				{
					"name": "S"
				},
				{
					"name": "X"
				}
			]
		},
		{
			"models": [
				{
					"name": "Zomeo"
				},
				{
					"name": "Caleo"
				}
			]
		}
	]
}

**Comment by christophlim** [comment]
> I had it working with this :
> 
> {d.title[i].text}	{d.title[i+1].text}
> {d.content[i].content[i].text}	{d.content[i].content[i+1].text}
> {d.content[i+1].content[i].text}	{d.content[i+1].content[i+1].text}
> ```
> {
>   title: [{text: 'Salutation'}, {text: 'lang'}],
>   content: [
>     {content: [{text: 'Hello'}, {text: 'en'}]},
>     {content: [{text: 'Bonjour'}, {text: 'fr'}]}
>   ]
> }
> ```
> 
> I never use a direct value from an array. `Array` contains `Object` which contains the value to use.
> 
> For the doc example, try by using something like that :
> 
> ```
> {
>   myArray : [{"brand": etc...}, {"brand": etc...]
> }
> ```
> 
> and changing the template with `d.myArray[i]`

Correct me if i'm wrong but..that example isn't using bi-directional looping is it? Isn't this just iterating 2 different arrays, one array in the header cells and one array for the data cells?

**Comment by officeutils** [comment]
@steevepay Is there any update here?

**Comment by steevepay** [comment]
Hello @officeutils, we need more time to solve bi-directional loops and it can't be solved in the coming sprints. We will share updates on the feed as soon as we work on it.

**Comment by samirotiv** [comment]
Spent two hours trying to get it to work and then found this thread. Any update on this or any workarounds?

**Comment by officeutils** [comment]
@samirotiv I found a temporary solution for my problem. I need to create multiple tables with 2-4 columns. Look at the attached picture.
![image](https://user-images.githubusercontent.com/5348737/149943719-ce6195bf-1df1-457b-ad10-77a6aa5afce4.png)

**Comment by dvernole** [comment]
Any news about this issue?

**Comment by enariavishenda** [comment]
delete from the main documentation, misled me, spent half a day

**Comment by dgrelaud** [comment]
Carbone v4.8.0 fixes lot of issues for bidirectional loop in DOCX templates.

The website has been updated: https://carbone.io/documentation.html#bi-directionnal-loop 

Here is a real life example: 

https://carbone.io/examples/bidirectional-loop/bidirectional-loop.zip 
![image](https://user-images.githubusercontent.com/1288509/225388156-4929c36f-65ea-4a08-95a3-ce3f0a0c4ae7.png)

We keep this issue opened. 
When Carbone v5 will be available. This repository will be updated with Carbone v4 and we will close this issue.

Feel free to contact us on the chat of the website if you need further help & information.
